language: erlang
notifications:
  recipients:
    - yuki@gnnk.net
otp_release:
  - 17.0
  - 17.1
env:
  - ELIXIR="v0.13.3"
  - ELIXIR="v0.14.0"
  - ELIXIR="v0.15.0"
  - ELIXIR="v0.15.1"
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/$ELIXIR/Precompiled.zip && unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
  - mix local.hex --force
script: mix test
